### ISSUE TITLE
How to nuke only specified resource types

### ISSUE THREAD

**Issue by jamesgeddes** [diodonfrost/terraform-aws-lambda-nuke#10]
Hi there,

Apologies in advance for the silly question!

How do you nuke only the specified resource type? For example, I only want to nuke,
 - S3Bucket
 - EC2Instance

Thanks

**Comment by marcransome** [comment]
See the documentation for the `exclude_resources` argument in the [inputs](https://github.com/diodonfrost/terraform-aws-lambda-nuke#inputs) section of the `README.md`—presumably this is used to populate the [EXCLUDE_RESOURCES](https://github.com/diodonfrost/terraform-aws-lambda-nuke/blob/master/package/nuke/main.py#L38) Lambda environment variable which excludes services defined in the [_strategy](https://github.com/diodonfrost/terraform-aws-lambda-nuke/blob/master/package/nuke/main.py#L46-L69) dictionary.

**Comment by jamesgeddes** [comment]
Thanks @marcransome - I missed that bit!

**Comment by jamesgeddes** [comment]
@marcransome Just read this again - can you see how to define the resources that _will_ be destroyed? Looks like `exclude_resources` defines the resources that will be _not_ destroyed.

**Comment by jamesgeddes** [comment]
Seems like the only way is to provide a list of all resources except ec2 and s3
