### ISSUE TITLE
Unable to remove ec2 instance

### ISSUE THREAD

**Issue by quickbooks2018** [diodonfrost/terraform-aws-lambda-nuke#2]
[WARNING]	2020-02-20T18:52:51.507Z	a2d2eb-2fc7-441b-8069-1983e7765bfe	security group sg-e15642ca: An error occurred (DependencyViolation) when calling the DeleteSecurityGroup operation: resource sg-e142ca has a dependent object

**Comment by diodonfrost** [comment]
its looks like the security group is still attached to an ec2 instance.
Maybe the instance is not fully deleted when the lambda function try to nuke this security group

**Comment by quickbooks2018** [comment]
Yes issue is in the code, my job done is via https://github.com/rebuy-de/aws-nuke

**Comment by diodonfrost** [comment]
Fixed in version [2.7.1](https://github.com/diodonfrost/terraform-aws-lambda-nuke/commit/ff78714f879a42b3c2499fb7526b810de4727125) with boto3 waiter.

**Comment by quickbooks2018** [comment]
Worked Thanks
